Handle exceptions in pynag command-line utility
* Introduce new option --debug to see tracebacks
* Otherwise print exception, but not stack trace
* Closes #13

Example:
$ pynag list
Error occured, use --debug to see full traceback:

OSError: [Errno 13] Permission denied: '/etc/nagios3/'