Fix TypeError in PynagError's __init__ due to Python 2.4
Python 2.4 Exception's are not new-style classes. Therefore, we cannot use
the super(Parent, self) syntax.

This fixes errors in test_invalid_threshold and test_invalid_range

      File "/home/nagios/pynag/pynag/Utils/__init__.py", line 48, in __init__
        super(self.__class__, self).__init__(message, *args,**kwargs)
    TypeError: super() argument 1 must be type, not classobj